number = float(input("Enter a float number: "))
rounded_number = round(number, 2)
print(f"Rounded number: {rounded_number}")
num1=float(input('enter the first number:'))
num2=float(input('enter the second number:'))
num3=float(input('enter the third number:'))
largest=max(num1,num2,num3)
smallest=min(num1,num2,num3)
print(f"The largest number is: {largest}")
print(f"The smallest number is: {smallest}") 
